# Generated by Django 2.2.5 on 2020-04-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_text', models.CharField(max_length=750, verbose_name='Секретный Текст')),
                ('secret_word', models.CharField(max_length=50, verbose_name='Кодовая Фраза')),
                ('secret_key', models.CharField(max_length=50, verbose_name='Секретный Ключ')),
                ('is_read', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания секрета')),
                ('lifetime', models.DateTimeField(verbose_name='Время жизни секрета')),
            ],
        ),
    ]
