# Generated by Django 2.2.5 on 2020-05-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_app', '0002_auto_20200429_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='lifetime',
            field=models.DurationField(verbose_name='Время жизни секрета'),
        ),
    ]
