# Generated by Django 2.2.5 on 2020-05-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_app', '0003_auto_20200501_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='secret_text',
            field=models.BinaryField(verbose_name='Секретный Текст'),
        ),
        migrations.AlterField(
            model_name='secret',
            name='secret_word',
            field=models.CharField(max_length=128, verbose_name='Кодовая Фраза'),
        ),
    ]
