# Generated by Django 2.2.5 on 2020-05-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_app', '0004_auto_20200504_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='secret_word',
            field=models.CharField(max_length=1000, verbose_name='Кодовая Фраза'),
        ),
    ]
